source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DQNetworkKit_Example', :exclusive => true do
  pod "DQNetworkKit", :path => "../"
end

target 'DQNetworkKit_Tests', :exclusive => true do
  pod "DQNetworkKit", :path => "../"

  
end
